
name: Bug report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: Clear and concise description...
  - type: textarea
    attributes:
      label: Steps to reproduce
  - type: input
    attributes:
      label: Environment
      placeholder: OS/Browser/Node version
  - type: textarea
    attributes:
      label: Screenshots/Logs
